import { alpha } from "@mui/material";
import fonts from "../../../fonts";

export const getRawMaterialProcurementTheme = (baseTheme: any) => {
	const palette = baseTheme?.palette ?? {};

	return {
		header: {
			accentChip: {
				background: alpha(palette.primaryLight ?? "#2E86C1", 0.1),
				color: palette.primary ?? "#1B4F72",
				border: `1px solid ${alpha(palette.primaryLight ?? "#2E86C1", 0.25)}`,
			},
		},
		specificationForm: {
			animatedBlockCard: (idx: number) => ({ animation: "fadeIn 0.3s ease both", animationDelay: `${idx * 0.06}s` }),
			editModeIcon: { fontSize: 18, flexShrink: 0 },
			iconBadge: {
				width: 30,
				height: 30,
				borderRadius: "8px",
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				boxShadow: `0 3px 8px ${alpha(palette.primary, 0.3)}`,
			},
			headerIconBadge: {
				width: 32,
				height: 32,
				borderRadius: "10px",
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				boxShadow: `0 4px 10px ${alpha(palette.primary, 0.3)}`,
			},
			headerScienceIcon: { fontSize: 17 },
			headerTitle: { fontWeight: fonts.weight.bold, fontSize: fonts.size.sm, color: palette.text },
			headerSubtitle: { fontSize: fonts.size.xs, color: palette.textSub, mt: 0.3 },
			whiteIcon: { color: "#fff" },
			blockScienceIcon: { fontSize: 16 },
			progressChipIcon: { fontSize: "13px !important" },
			blockTitle: { fontWeight: fonts.weight.bold, fontSize: fonts.size.xs, color: palette.text },
			blockMeta: { fontSize: "0.68rem", color: palette.textSub },
			progressChip: (allFilled: boolean) => ({
				height: 22,
				fontSize: "0.65rem",
				fontWeight: 700,
				background: allFilled ? alpha(palette.accent, 0.1) : alpha(palette.warn, 0.1),
				color: allFilled ? palette.accent : palette.warn,
				border: `1px solid ${allFilled ? alpha(palette.accent, 0.25) : alpha(palette.warn, 0.3)}`,
			}),
			removeIconButton: { color: palette.danger, "&:hover": { background: alpha(palette.danger, 0.08) } },
			lotField: { minWidth: 130, "& .MuiInputBase-input": { fontSize: "0.78rem", padding: "5px 10px" } },
			specText: { fontSize: "0.8rem", color: palette.text, fontWeight: 500 },
			refRangeChip: {
				mt: { xs: 1.5, md: 0 },
				minWidth: 150,
				fontSize: fonts.size.xs,
				fontWeight: fonts.weight.bold,
				background: alpha(palette.warn, 0.1),
				color: palette.warn,
				border: `1px solid ${alpha(palette.warn, 0.3)}`,
			},
			analyzedField: { width: 120, "& .MuiInputBase-input": { fontSize: "0.78rem", padding: "5px 10px" } },
			remarksField: { width: 200, "& .MuiInputBase-input": { fontSize: "0.78rem", padding: "4px 8px", lineHeight: 1.5 } },
			editModeBanner: {
				mb: 2.5,
				px: 2,
				py: 1.5,
				borderRadius: 2,
				background: alpha(palette.danger, 0.05),
				border: `1.5px solid ${alpha(palette.danger, 0.2)}`,
				display: "flex",
				alignItems: "center",
				gap: 1.2,
			},
			editModeBannerText: { fontSize: "0.8rem", color: palette.danger, fontWeight: 600, lineHeight: 1.5 },
			summaryChip: { fontWeight: 700, fontSize: "0.7rem" },
			summaryPrimaryChip: {
				fontWeight: 700,
				fontSize: "0.7rem",
				background: alpha(palette.primaryLight, 0.12),
				color: palette.primary,
			},
			resultSummaryChip: (allFilled: boolean) => ({
				fontWeight: 700,
				fontSize: "0.7rem",
				background: allFilled ? alpha(palette.accent, 0.12) : alpha(palette.warn, 0.12),
				color: allFilled ? palette.accent : palette.warn,
			}),
			materialSelectorBox: {
				p: "14px 18px",
				borderRadius: 3,
				mb: 2.5,
				background: `linear-gradient(135deg, ${alpha(palette.primary, 0.04)}, ${alpha(palette.primaryLight, 0.03)})`,
				border: `1.5px dashed ${alpha(palette.primaryLight, 0.35)}`,
			},
			materialOption: { fontWeight: 600, fontSize: "0.85rem" },
			materialOptionMeta: { ml: 1, fontSize: "0.72rem", color: palette.textSub },
			addButton: {
				borderRadius: 2.5,
				fontWeight: 800,
				fontSize: "0.8rem",
				textTransform: "none",
				px: 3,
				py: "9px",
				background: `linear-gradient(135deg, ${palette.primary}, ${palette.primaryLight})`,
				boxShadow: `0 4px 14px ${alpha(palette.primary, 0.35)}`,
				whiteSpace: "nowrap",
				minWidth: 140,
				"&:hover": { boxShadow: `0 6px 18px ${alpha(palette.primary, 0.45)}`, transform: "translateY(-1px)" },
				"&:disabled": { background: palette.border, boxShadow: "none", color: palette.textSub },
				transition: "all 0.25s cubic-bezier(0.34,1.56,0.64,1)",
			},
			emptyStateTitle: { fontWeight: 600, color: palette.textSub, fontSize: "0.88rem" },
			emptyStateSubtitle: { fontSize: "0.75rem", color: alpha(palette.textSub, 0.7), mt: 0.5 },
			emptyStateIcon: { fontSize: 36, color: palette.border, mb: 1.5 },
			footerInfoContainer: { mt: 2.5, px: 2, py: 1.2 },
			footerInfoIcon: { fontSize: 15, color: palette.primaryLight, flexShrink: 0 },
			footerInfoText: { fontSize: "0.72rem", color: palette.textSub, lineHeight: 1.5 },
			tableHeader: {
				material: { minWidth: 80 },
				lotBatch: { minWidth: 150 },
				specification: { minWidth: 200 },
				refRange: { minWidth: 130 },
				analysedResult: { minWidth: 140 },
				remarks: { minWidth: 200 },
			},
			dataRow: (rowIndex: number) => ({
				"&:hover": { background: alpha(palette.primaryLight, 0.03) },
				"&:last-child td": { borderBottom: "none" },
				background: rowIndex % 2 === 0 ? palette.surface : alpha(palette.surface, 0.6),
			}),
		},
		specification: {
			panelBorder: alpha(palette.primaryLight ?? "#2E86C1", 0.28),
		},
	};
};

export default getRawMaterialProcurementTheme;
